### ISSUE TITLE
Clarification: X/Y offsets

### ISSUE THREAD

**Issue by bradanlane** [technoblogy/tiny-tft-graphics-library#3]
For each screen there are several values defined. The size is pretty self explanatory. However, the "offset" values do not detail a source.

Are the values of the X/Y offsets from a datasheet? determined through trial and error? some other source?

**Comment by technoblogy** [comment]
They depend on the wiring between the physical display and the display controller, and this isn't generally published, so I used trial and error, adjusting the values until the `TestChart()` routine gave a centred display.
